Try with libboost-devel 1.82
Last successful build was with 1.82
With 1.84 it fails with:
```
include/boost/progress.hpp:23:3: error: #error This header is deprecated and will be removed. (You can define BOOST_TIMER_ENABLE_DEPRECATED to suppress this error.)
2024-07-30T07:49:45.0579220Z    23 | # error This header is deprecated and will be removed. (You can define BOOST_TIMER_ENABLE_DEPRECATED to suppress this error.)
```

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>